server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 設置為 true 時，Spring Cloud Gateway 會自動為每個從服務發現服務中獲取到的服務配置路由
#          lower-case-service-id: true # 屬性設置為 true 可以將服務的 ID 轉換為小寫，以避免路徑匹配時的大小寫敏感問題。
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: order-lines-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**