server:
  port: 8050
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # 需先創建product DB
    url: jdbc:postgresql://localhost:5432/product
    username: alix
    password: alix
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
